### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by Netherdrake** [rllola/zeroTube#19]
I am sorry I'm new to node.js, and there is no Dockerfile to help out.

I'm trying to run the project, but I get this error:

```
~/S/G/zeroTube % gulp watch
[21:15:30] Using gulpfile ~/Sync/GitHub/zeroTube/gulpfile.js
[21:15:30] Starting 'clean:build'...
[21:15:30] Finished 'clean:build' after 6.16 ms
[21:15:30] Starting 'build'...
[21:15:30] Starting 'watch:build'...
[21:15:30] 'watch:build' errored after 22 ms
[21:15:30] Error: watch /home/tom/Sync/GitHub/zeroTube/app/ ENOSPC
    at exports._errnoException (util.js:907:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at Gaze._watchDir (/home/tom/Sync/GitHub/zeroTube/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /home/tom/Sync/GitHub/zeroTube/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/tom/Sync/GitHub/zeroTube/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/tom/Sync/GitHub/zeroTube/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/tom/Sync/GitHub/zeroTube/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/tom/Sync/GitHub/zeroTube/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/tom/Sync/GitHub/zeroTube/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
[21:15:42] Version: webpack 1.13.2
            Asset     Size  Chunks             Chunk Names
 public/js/all.js  2.18 MB       0  [emitted]  main
public/js/all.map  2.56 MB       0  [emitted]  main

WARNING in ./~/webtorrent/webtorrent.min.js
Critical dependencies:
1:418-425 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/webtorrent/webtorrent.min.js 1:418-425

ERROR in ./app/util/constants.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../content.json in /home/tom/Sync/GitHub/zeroTube/app/util
 @ ./app/util/constants.js 3:15-44

ERROR in ./~/webtorrent/webtorrent.min.js
Module not found: Error: Cannot resolve module 'jquery' in /home/tom/Sync/GitHub/zeroTube/node_modules/webtorrent
 @ ./~/webtorrent/webtorrent.min.js 1:0-17

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in /home/tom/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 7:16-56

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/objectWithoutProperties' in /home/tom/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 11:32-88

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in /home/tom/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 15:23-70

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in /home/tom/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 19:20-64

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in /home/tom/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 23:34-92

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in /home/tom/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 27:17-58
[21:15:42] Finished 'build' after 13 s
~/S/G/zeroTube % 
```

```
~/S/G/zeroTube % node --version
v4.6.0
```

**Comment by rllola** [comment]
Have you done
`$ npm install` ?

**Comment by Netherdrake** [comment]
```
~/S/GitHub % cd zeroTube/
~/S/G/zeroTube % git pull
Already up-to-date.
~/S/G/zeroTube % npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/babel-cli/node_modules/chokidar/node_modules/fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (c
urrent: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/gulp-nodemon/node_modules/nodemon/node_modules/c
hokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (c
urrent: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/webpack/node_modules/watchpack/node_modules/chok
idar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (c
urrent: {"os":"linux","arch":"x64"})
npm WARN zerotube@0.3.2 No repository field.
~/S/G/zeroTube % ls
app/                  data/          gulpfile.js  node_modules/  public/    rtcConfig.json
content.json.example  dbschema.json  index.html   package.json   README.md  webpack.config.js
```

```
~/S/G/zeroTube % npm start

> zerotube@0.3.2 start /home/x/Sync/GitHub/zeroTube
> gulp

[18:51:10] Using gulpfile ~/Sync/GitHub/zeroTube/gulpfile.js
[18:51:10] Starting 'clean:build'...
[18:51:10] Finished 'clean:build' after 3.42 ms
[18:51:10] Starting 'build'...
[18:51:10] Starting 'watch:build'...
[18:51:10] Finished 'watch:build' after 16 ms
[18:51:18] Version: webpack 1.13.2
            Asset     Size  Chunks             Chunk Names
 public/js/all.js  2.46 MB       0  [emitted]  main
public/js/all.map  2.91 MB       0  [emitted]  main

~/S/GitHub % cd zeroTube/
~/S/G/zeroTube % git pull
Already up-to-date.
~/S/G/zeroTube % npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/babel-cli/node_modules/chokidar/node_modules/fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (c
urrent: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/gulp-nodemon/node_modules/nodemon/node_modules/c
hokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (c
urrent: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/webpack/node_modules/watchpack/node_modules/chok
idar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (c
urrent: {"os":"linux","arch":"x64"})
npm WARN zerotube@0.3.2 No repository field.
~/S/G/zeroTube % ls
app/                  data/          gulpfile.js  node_modules/  public/    rtcConfig.json
content.json.example  dbschema.json  index.html   package.json   README.md  webpack.config.js

Critical dependencies:
1:418-425 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/webtorrent/webtorrent.min.js 1:418-425

ERROR in ./app/util/constants.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../content.json in /home/x/Sync/GitHub/zeroTube/app/util
 @ ./app/util/constants.js 3:15-44

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/extends' in /home/x/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 7:16-56

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/objectWithoutProperties' in /home/x/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 11:32-88

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in /home/x/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 15:23-70

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/createClass' in /home/x/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 19:20-64

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in /home/x/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 23:34-92

ERROR in ./~/react-truncate/lib/Truncate.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in /home/x/Sync/GitHub/zeroTube/node_modules/react-truncate/lib
 @ ./~/react-truncate/lib/Truncate.js 27:17-58

```

**Comment by danimesq** [comment]
@rllola
Why it needs Node.js?

**Comment by Powersource** [comment]
Ran `npm install` and `npm start` (would be good with instructions for this in the repo) and am getting:

```
WARNING in ./~/webtorrent/webtorrent.min.js
Critical dependencies:
1:418-425 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/webtorrent/webtorrent.min.js 1:418-425

ERROR in ./~/bootstrap/dist/js/bootstrap.min.js
Module not found: Error: Cannot resolve module 'jquery' in /mnt/hdd/home/me/prj/web/zeroTube/node_modules/bootstrap/dist/js
 @ ./~/bootstrap/dist/js/bootstrap.min.js 1:0-17

ERROR in ./app/util/constants.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../content.json in /mnt/hdd/home/me/prj/web/zeroTube/app/util
 @ ./app/util/constants.js 3:15-44

ERROR in ./~/webtorrent/webtorrent.min.js
Module not found: Error: Cannot resolve module 'jquery' in /mnt/hdd/home/me/prj/web/zeroTube/node_modules/webtorrent
 @ ./~/webtorrent/webtorrent.min.js 1:0-17
```
